services:
  backend:
    profiles:
      - dev
    build:
      context: ./backend/rest-api
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    networks: [app_network]
    ports:
      - "3001:3001"
    volumes:
      - ./backend/rest-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coding_task
    depends_on:
      - postgres

  frontend:
    profiles:
      - dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    hostname: frontend
    networks: [app_network]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
